[package]
name = "pointers"
version = "0.1.0"
authors = ["Abhirup <abhidash@outlook.com>"]
edition = "2018"

include = ["src/**/*"]
# workspace = "../pointers"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
